version: '1.0.{build}'

shallow_clone: false

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

image:
  - Visual Studio 2019
  - Visual Studio 2022

cache:
  - C:\cmake-3.24.3-windows-x86_64

install:
  - git submodule update --init --recursive
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.24.3-windows-x86_64\bin\cmake.exe")) {
        Start-FileDownload 'https://github.com/Kitware/CMake/releases/download/v3.24.3/cmake-3.24.3-windows-x86_64.zip'
        7z x -y cmake-3.24.3-windows-x86_64.zip -oC:\
      }
      $env:PATH="C:\cmake-3.24.3-windows-x86_64\bin;$env:PATH"

build: script

build_script:
  - ps: |
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2019") {
          .\build.ps1 -VisualStudioVersion Vs2019 -Runtime All -Platform $env:PLATFORM -Config $env:CONFIGURATION -Package
      } else {
          .\build.ps1 -VisualStudioVersion Vs2022 -Runtime All -Platform $env:PLATFORM -Config $env:CONFIGURATION -Package
      }

test_script:
  - ps: |
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2019") {
          $TestExecutable = 'build_Vs2019_' + $env:PLATFORM + '_static\test\lib\' + $env:CONFIGURATION + '\lib_tests.exe'
      } else {
          $TestExecutable = 'build_Vs2022_' + $env:PLATFORM + '_static\test\lib\' + $env:CONFIGURATION + '\lib_tests.exe'
      }
      & $TestExecutable --gtest_output=xml:test_results.xml
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test_results.xml))

artifacts:
  - path: package\*.zip

deploy:
  description: 'win32cpp release'
  provider: GitHub
  auth_token:
    secure: W3zRbfLgxfhwtRrkDovlbGExTZfUPel+INLDsV9cn8XV6tOs3A/hm5F5dswHYmcH
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

notifications:
  - provider: Email
    to:
      - lordjeb@lordjeb.com
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false