#pragma once
#include "win32api_abstractions.h"

struct mock_file : public win32cpp::ioc::IFile
{
	MOCK_METHOD1(CloseHandle, BOOL(HANDLE));
	MOCK_METHOD7(CreateFileA, HANDLE(LPCSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE));
	MOCK_METHOD7(CreateFileW, HANDLE(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE));
	MOCK_METHOD6(CreateFileMappingA, HANDLE(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCSTR));
	MOCK_METHOD6(CreateFileMappingW, HANDLE(HANDLE, LPSECURITY_ATTRIBUTES, DWORD, DWORD, DWORD, LPCWSTR));
	MOCK_METHOD5(MapViewOfFile, LPVOID(HANDLE, DWORD, DWORD, DWORD, SIZE_T));
	MOCK_METHOD1(UnmapViewOfFile, BOOL(LPCVOID));
};
